apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: anti

resources:
- ../demo-app
- namespace.yaml

patches:
- path: deployment.yaml
  target:
    kind: Deployment

replicas:
- name: demo
  count: 5
